# Generated by Django 4.2 on 2023-04-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, verbose_name='Последние 4 цифры номера карты')),
                ('payment_id', models.CharField(blank=True, max_length=50, verbose_name='ID платежа')),
                ('status', models.CharField(choices=[('PND', 'Ожидает подтверждения'), ('SCS', 'Оплачен'), ('CNC', 'Отменен')], default='PND', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sitestorage.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
