# Generated by Django 4.2 on 2023-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0002_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='address',
            field=models.CharField(default='a', max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='occupied',
            field=models.IntegerField(default=0, verbose_name='Занято боксов'),
        ),
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Доступное количество боксов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='temperature',
            field=models.IntegerField(default=18, verbose_name='Температура в боксе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='title',
            field=models.CharField(blank=True, default='a', max_length=30, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='title',
            field=models.CharField(blank=True, default='a', max_length=10, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='a', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
