# Generated by Django 4.2 on 2023-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0003_storage_address_storage_occupied_storage_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='some_user', max_length=250, verbose_name='Имя'),
        ),
    ]
