# Generated by Django 4.2 on 2023-04-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес склада',
                'verbose_name_plural': 'Адреса складов',
            },
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitestorage.storageaddress', verbose_name='Адрес'),
        ),
    ]
