# Generated by Django 4.2 on 2023-04-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0005_storageaddress_alter_storage_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='sitestorage.storageaddress', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Высота, м'),
        ),
    ]
