# Generated by Django 4.2 on 2023-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0006_alter_storage_address_alter_storage_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото контейнера'),
        ),
    ]
