# Generated by Django 4.2 on 2023-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0007_alter_storage_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='quantity',
        ),
        migrations.AddField(
            model_name='storageaddress',
            name='occupied',
            field=models.IntegerField(default=0, verbose_name='Занято боксов'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование'),
        ),
    ]
