# Generated by Django 4.2 on 2023-04-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0008_remove_storage_occupied_remove_storage_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cargo',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_payments', to='sitestorage.storage', verbose_name='Хранилище'),
            preserve_default=False,
        ),
    ]
