# Generated by Django 4.2 on 2023-04-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestorage', '0009_remove_order_cargo_paymentorder_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sitestorage.order', verbose_name='Заказ'),
        ),
    ]
